### PR TITLE
Synchronized  UnsignedXYTypes

### PR DESCRIPTION
**Pull request by dietzc**
parallel access on these types caused problems. it was fixed for BitType, but not for the remaining types.

See https://github.com/imglib/imglib2/tree/synchronized-bit-access for details.

### CODE REVIEW

**Comment by tpietzsch** [comment]
@dietzc: Unsigned128BitType does not need to be synchronized. There is no conflict there: Each value spans exactly two longs, so no element of the underlying primitive array is shared by more than two values. Please remove this commit.
The remaining type that needs to be synchronized (as far as I can see) is ```AbstractBit64Type``` (which is extended by ```BasePairBitType``` and ```UnsignedVariableBitLengthType```). Could you add synchronization for that as well?

**Comment by dietzc** [comment]
done. build still works. something else missing?

**Comment by tpietzsch** [comment]
@dietzc Hmm, you overdid it a bit... Get()s don't have to be synchronized. I fixed that and also moved some computations out of the synchronize blocks. Can you please verify that your stuff works with this?

**Comment by tpietzsch** [comment]
@dietzc Did you run the KNIP test already?

**Comment by dietzc** [comment]
nope, not yet! I will test it today!

**Comment by dietzc** [comment]
:+1: go!

can you release imglib2 and imglib2-algorithm?

**Comment by tpietzsch** [comment]
@dietzc I would wait until the morphology package is merged before releasing imglib2-algorithm.

**Comment by acardona** [comment]
Hi @tpietzsch , @dietzc , wouldn't it have made more sense to create extended classes to overwrite the methods to be synchronized? E.g. SynchronizedUnsigned4BitType extends Unsigned4BitType ... and then extend just the methods that need synchrized (dataAccess) ? The way you are doing it now forces all uses of these types to be synchronized, even when the synchronization is not necessary.

**Comment by tpietzsch** [comment]
@acardona @dietzc If one of you wants to give this a try please go ahead!

**Comment by dietzc** [comment]
I won't find time to do that. I also don't understand how this would work (even if it would be nice to have it). If I get a `RandomAccessibleInterval<T>` with `T extends RealType<T>` as the input for my algorithm which is paralellized, how would I change the type of the `T` to something which is thread-safe (or not)?

**Comment by acardona** [comment]
@dietzc Picture the case where it is better to process multiple images with one thread each rather than one single image with many threads. For the earlier case the synchronization is an unnecessary overhead.

I agree though that the default approach is to assume types are internally self-consistent when it comes to read/write into their underlying container. So I would favor the approach where an "unsafe" subpackage contains the fast UnsynchronizedXYBitType versions, differing only in the write methods.

@tpietzsch By the way the get method is also unsafe and should be synchronized given that it reads from a container that can be written to simultaneously by another thread in ways that do not guarantee atomicity at the single array slot entry point like for the other types.

**Comment by dietzc** [comment]
@acardona I understand the use-case, this actually our main use-case with KNIME :-). But if I understand correctly, then you have to decide which type you want to use right when the image is created (e.g. in the `ImgOpener`) and this type is then propagated through your complete program (assuming you don't add any instance-of checks and use algorithms which are independent of the type). Right?

**Comment by tpietzsch** [comment]
@acardona That is ok. If one pixel is touched by multiple threads at the same time, the results are undefined. In this respect this is similar to ```ComplexDoubleType```. If you write and read the same pixel of ```ComplexDoubleType``` from two threads, you may also see inconsistent results because writes are not atomic. The difference in the BitTypes is that the write touches multiple pixels. Assume that four bits from the same long are ```0100``` and thread A wants to reads the second bit of those while thread B sets the fourth bit to ```1```. Then it doesn't matter whether thread A sees the value before or after the write. It gets ```0100``` or ```0101``` and it doesn't matter which because in the second bit it is unchanged.
For the imglib2 types we implicitly guarantee the same behaviour as primitive arrays. For example, if you have a ```long[] array``` and simultaneously read and write ```array[0]``` it is not guaranteed that the read does not happen in the middle of the write, because ```long``` writes are not atomic. It is guaranteed however that simultaneously writing ```array[0]``` and ```array[1]``` will not influence each other. As I said, this is an implicit guarantee which is just the interpretation of how all the types behaved before the fraction branch was merged. The fraction branch broke the behaviour and this PR fixed it. I think the implicit guarantee should be made explicit in the documentation.

**Comment by acardona** [comment]
@dietzc For the Unsigned12BitType yes. For the others, my only use has been for special-purpose applications like storing feature vectors in a compact manner, or for avoiding using a full long because an integer range is no enough for e.g. integral histograms. So: more for results of computations rather than for reading files from disk.

**Comment by acardona** [comment]
@tpietzsch OK great, just thought of pointing that out.

**Comment by dietzc** [comment]
@acardona ah! this absolutely makes sense. thanks for clarifying.

**Comment by tpietzsch** [comment]
@dietzc Do you have a small multi-threaded example that I could use to test correctness and performance when evaluating the synchronized vs a lock-free approch?

**Comment by dietzc** [comment]
unfortunately not, I always tested it with our KNIME test-flows.

**Pull request merged**
