### PR TITLE
Views dimension validation

### PR DESCRIPTION
**Pull request by etarena**
This branch addresses #141, adding dimensionality checks for Views methods.

### CODE REVIEW

**Comment by axtimwalde** [comment]
Hi @etarena , we chose to not test various conditions at runtime to make Views as performant as possible.  Assertions are in place to test the minimal requirements for debugging.  I am therefore voting strongly against accepting this pull request.  If you need to perform these tests at runtime in an application, please do so outside of imglib2 core.

**Comment by ctrueden** [comment]
@axtimwalde Do you have any real use cases where you need to call Views millions of times where these checks will actually make a significant difference?

As things stand, Views is _very_ heavily used and recommended, and yet when you make simple common mistakes such as passing a 2D min/max array with a 3D image, you get a totally arcane and impenetrable exception. This sucks, and we can do better.

**Comment by axtimwalde** [comment]
@ctrueden yes, we are calling views rapidly during optimization.  The tests do not make a big difference, I agree, but we generally do not perform runtime input validations in ImgLib2 anywhere to maximize algorithm performance.  Helpful debugging output is supported via assertions.  I suggest to perform runtime tests outside of core closer to applications where this is desired, e.g. Ops.  Does that work for you?

**Comment by ctrueden** [comment]
> I suggest to perform runtime tests outside of core closer to applications where this is desired, e.g. Ops. Does that work for you?

OK.

**Comment by StephanPreibisch** [comment]
I agree with @axtimwalde ... once we start checking things it is unclear where to draw the line of what to check, which at the end makes the framework more unpredictable in my opinion, even not considering performance aspects.

**Comment by tpietzsch** [comment]
@StephanPreibisch That was exactly my concern with this PR. I was actually tempted to just merge it because in this case it wouldn't be much overhead, but it is difficult to know where to stop. It's cleaner to have a policy of not doing safety checks anywhere.

**Comment by ctrueden** [comment]
I am willing to respect this decision in the ImgLib2 space. But I do feel compelled to chime in that I disagree with this sort of [slippery slope](https://en.wikipedia.org/wiki/Slippery_slope) argument. This is a gray area of balancing performance with usability. My argument here, and the reason for this PR, is because @etarena and I found `Views` to be difficult to use due to the arcane `ArrayIndexOutOfBoundsException`, and thought that adding some basic dimensional length checks would make things much easier for users, especially new users such as @etarena, while not impacting performance negatively much if at all. This was not the first time I have received, and/or seen others receive, these sorts of arcane exceptions. They contribute to the perception of new users that ImgLib2 is deep and complicated and hard to learn and use—which I think has a lot of truth actually, and I would like us to do whatever we can to make it easier to adopt and use.

On my end, I will do as @axtimwalde suggests and shift that balance more toward usability in ImageJ, especially ImageJ Ops. Then I can simply tell new users to use ImageJ, since it builds a lot of niceties on top of ImgLib2 and is much easier to learn.

**Pull request closed without merging**
