### PR TITLE
Improve ImgFactory generics

### PR DESCRIPTION
**Pull request by ctrueden**
See #91.

We may want to hold off on merging this until a couple of last implementation details are sorted out.

### CODE REVIEW

**Comment by ctrueden** [comment]
It's almost ready, but I just noticed I missed updating the `PlanarImgFactory` and `NtreeImgFactory`. I have to run now. Will try to clean up and finalize this later tonight if time.

**Comment by tpietzsch** [comment]
no hurry

**Comment by ctrueden** [comment]
Should be ready to go now.

**Comment by ctrueden** [comment]
Ran up against `ImgFactory` generics issues again today—are we still planning to merge this?

**Comment by tpietzsch** [comment]
the plan is to merge it as part of #197. I'll try to spend some time on that soon, address @maarzt comments and the merge ASAP.

**Comment by tpietzsch** [comment]
merged as part of #197.

**Pull request closed without merging**
