### PR TITLE
Constant accesses

### PR DESCRIPTION
**Pull request by hanslovsky**
Constant access always return the same value.

### CODE REVIEW

**Comment by tpietzsch** [comment]
What is the purpose?

**Comment by hanslovsky** [comment]
For propagation of painted data to higher resolution scales in multi-scale painting, I would like to be able to set complete blocks to a constant value without touching every single pixel. Ideally, this can also be persisted to disk with disk cached cell imgs.

**Comment by hanslovsky** [comment]
I am currently trying to cache these constant cells to disk, and I noticed that the hierarchy should be slightly different.

**Comment by tpietzsch** [comment]
I think it would be better to put these classes into your own project until it has proven useful? Then migrate to `imglib2` once it settled. The same way as the `Volatile` accesses started in bdv...

**Comment by hanslovsky** [comment]
I can live with that.

**Comment by tpietzsch** [comment]
👍

**Pull request closed without merging**
