### PR TITLE
Add TiledView and GridView

### PR DESCRIPTION
**Pull request by gab1one**
All work done by @MarcelWiedenmann.

### CODE REVIEW

**Comment by ctrueden** [comment]
What is the plan? Are the commits going to be cleaned up? Or did you just want to let this sit?

**Comment by frauzufall** [comment]
Hey! We would love to work with this, can we help somehow to get this into master and a near future maven release?

**Comment by ctrueden** [comment]
@gab1one @MarcelWiedenmann Are you guys planning to get this PR to a mergeable state? Or do you need assistance?

**Comment by StephanPreibisch** [comment]
Hi, this code also overlaps with implementations we did in the multiview-reconstruction, which are quite well-tested by now. I would like to discuss these in more detail before adding such methods to core.

**Comment by gab1one** [comment]
Yes we originally intended to discuss this during the hackathon, I just cleaned up the commits, but @MarcelWiedenmann and @HedgehogCode and @dietzc know more about it.

@stelfrich can you point me to your methods in multiview-reconstruction? So we can check out if it covers our use cases as well?

**Comment by dietzc** [comment]
@StephanPreibisch could your code be ported to imglib2 core? We need this functionality quite often, but we don't really want a dependency on multiview reconstruction (quite a big project). Maybe we can join efforts and integrate what you have in multi-view reconstruction into this PR (if something is missing) and optimize the code such that we can in the end merge it into imglib2-core?

**Comment by dietzc** [comment]
@tpietzsch what about this PR? is there anything we can do to make it good enough to merge?

**Comment by tpietzsch** [comment]
@dietzc I'm looking at it only now, sorry :-(
Resolving merge conflicts and fixing formatting would be a good start.

**Comment by tpietzsch** [comment]
@dietzc From what I can see, `ArrangedView` is the same as `ListImg`?

**Comment by gab1one** [comment]
I removed the conflict and updated the formatting.

**Comment by gab1one** [comment]
> @dietzc From what I can see, ArrangedView is the same as ListImg?
In a sense yes, but `ArrangedView` con only contain RAI's and it knows about the arrangement, so that you can iterate over the arranged view as if it was one large image.

**Comment by tpietzsch** [comment]
> In a sense yes, but ArrangedView con only contain RAI's and it knows about the arrangement, so that you can iterate over the arranged view as if it was one large image.

Not true.
I think you are talking about `CombinedView`?

**Comment by gab1one** [comment]
Yes I was mistaken, still the arranged view knows about the grid alignment while the ListImg does not, it makes the CombinedView possible.

**Comment by tpietzsch** [comment]
If by grid alignment you mean that flat list indices are arranged in a nD grid, then yes, `ListImg` also knows about grid alignment

**Comment by gab1one** [comment]
Ok I took a closer look at `ListImg`, you are completely right, the Arranged View does exactly the same things, It should be easy to convert our code to use it instead and remove it.

**Comment by tpietzsch** [comment]
👍

**Comment by tpietzsch** [comment]
I would not put the `arrange` method in Views. I;m not sure it's needed on its own. If it is, I would put it in `ListImgs` (analogous to `ArrayImgs.bytes( final byte[] array, final long... dim )` etc. This looks like the same pattern: Here is flat data, wrap it into ListImg with the following dimensions...

Are there suggestions for better names for `CombinedView`. "Combined" is very generic, is there something that explains better what this actually does? Only thing I can think of quickly is `StitchedView`, but that also doesn't fit perfectly.

**Comment by ctrueden** [comment]
Here are some words! `tile`, `mosaic`, `montage`, `grid`, `fuse`, `aggregate`, `combine`, `assemble`

I don't know the difference between "tile" vs "combine" vs "arrange" here, so I'll decline to be more specific. ;-)

**Comment by frauzufall** [comment]
Or PatchedView.

**Comment by gab1one** [comment]
I chose the name `GridView` and removed ArrangedView. I hope it is now in a state closer to be merged.

**Comment by ctrueden** [comment]
@tpietzsch @gab1one Would it make sense to finalize this PR in person before the hackathon ends? Let me know if/how I can help.

**Comment by frauzufall** [comment]
Hi all, what's the current status for this PR? Is there still work to be done or is there an alternative to this approach by now?

**Comment by MarcelWiedenmann** [comment]
There is still work to be done. I believe @tpietzsch had some additional inline comments on the code, besides the ones in this thread. I can't them find anymore, though. Maybe they have been overwritten by a force push or so in the meantime.
I would gladly spend some time on this at the Dresden hackathon, but would first need to figure out what is left to do.

**Comment by tpietzsch** [comment]
Here are my additional comments, dug up from a private gitter conversation and translated to english...

1.)
I would not do `Views.zeroMin()` for `TiledView`. If one wants to do that, it can be done outside. (Whereas there is no easy way to recover the min/max of a tile after it has been "`zeroMin`ed").

2.)
The added `Views` methods need javadoc.

3.)
Consider removing the `Views.grid( final List< RandomAccessibleInterval< T > > source, final long... grid )` method.
This can be simply replaced by `Views.grid( Views.arrange( ... ) )`, which seems convenient enough.

4.)
[This is a memory leak](https://github.com/imglib/imglib2/pull/179/files#diff-859cac58518c776316d0f85f6da2528fR163) if it is backed by imglib2-cache.
Those RandomAccesses potentially reference cached cells, preventing these from being garbage-collected. You should use `WeakRefs` instead. Maybe have a look at this PR, where a similar problem is fixed: https://github.com/bigdataviewer/bigdataviewer-vistools/pull/16/files

5.) TiledView should probably split in two parts:
(1) Tiling of an `Interval` into smaller intervals, and
(2) Given ein `RandomAccessibleInterval<Interval>` that you got from (1), cut these pieces from a `RandomAccessibleInterval<T>`.
Several variants of (1) could be implemented: with or without overlap, regular or not, etc, and (2) can be reused every time.

6.) _[Translator's Note: I would have to  dig into the code again to find out what I meant exactly with the following.]_ `GridView` implementation is not very efficient  but it's fine doing it like this for now.

I suggest to try to generalize and re-use elements of `CellImg`.
For example, there is [`CellGrid`](https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/img/cell/CellGrid.java), which does the computations on intervals (computing min/max of a cell, translating between local, grid, and global coordinates). There is a lot of potential for re-use.

**Comment by frauzufall** [comment]
Ping @MarcelWiedenmann, this would be such a useful feature :)

**Comment by MarcelWiedenmann** [comment]
Oh boy - time really flies. I'll try to find some time during the coming semester break to work on it :).

**Comment by StephanPreibisch** [comment]
Hi, I started looking at this ... will try to discuss it next week with @axtimwalde. We all have a lot of similar code and this is a can of worms...

**Comment by ctrueden** [comment]
@tpietzsch Since you closed it, I assume something like this exists now? Could you please add a pointer to where the relevant functionality lives?

**Comment by tpietzsch** [comment]
Hmm, unfortunately not. I just closed it because there has been no progress on the actual code since 2017.

**Comment by tpietzsch** [comment]
Feel free to reopen. But maybe it would be better to move this to an issue?

**Pull request closed without merging**
