### PR TITLE
WIP Add benchmarks to measure performance problems for View.translate() etc.

### PR DESCRIPTION
**Pull request by maarzt**
The problems with the just in time compiler code optimization can
be potentially be triggered for:
* Converts.convert()
* Views.translate()
* Views.extendBorder() etc.

### CODE REVIEW

**Comment by maarzt** [comment]
@tpietzsch Here are that benchmarks that I talked about.

(The PR is intended to be a draft PR but I clicked the wrong button :upside_down_face:)

**Comment by tpietzsch** [comment]
Great! I think, it's very important to have these benchmarks to track progress.
Do you think any of these problems could/should be solved with `ClassCopyProvider`?

**Comment by tpietzsch** [comment]
Can you please format it with imglib2 code style, then I would just merge it

**Comment by maarzt** [comment]
I formatted the files according to the imglib2 coding style. So it can be merged now.

`ClassCopyProvider` could potentially be used to work around this performance problems. But that's not going to be easy, as this might cause new performance problems.

**Comment by axtimwalde** [comment]
Can this be merged?

**Pull request merged**
