### PR TITLE
add view to drop unit dimensions

### PR DESCRIPTION
**Pull request by dietzc**

### CODE REVIEW

**Comment by tpietzsch** [comment]
@dietzc, @tinevez, I like "Singleton" better that unit (because unit is easier confused with having something to do with the units of the axes). I don't like squeeze that much. How about ```dropSingletonDimensions```?

**Comment by dietzc** [comment]
I like it. @tinevez?

**Comment by tinevez** [comment]
Good!

**Comment by dietzc** [comment]
done

**Comment by tpietzsch** [comment]
@dietzc Could you use the imglib2 source formatting please?

**Comment by dietzc** [comment]
sorry forgot to re-add it. fine now?

**Comment by tpietzsch** [comment]
thanks

**Pull request merged**
