### PR TITLE
Add LinearAccessible interface and Views

### PR DESCRIPTION
**Pull request by hanslovsky**
`LinearAccessible` can be accessed through a linear index by a `LinearAccess`. This allows very fast access for certain types of `RandomAccessibleInerval`, e.g. `ArrayImg`. `Views.linearAccess` allows to access any `RandomAccessibleinerval` by linear index, using fast implementations where available.

### CODE REVIEW

**Comment by axtimwalde** [comment]
Thanks @hanslovskyp, not yet merge ready, so I am closing this pull request.
What do you think about not introducing an additional interface but instead implementing the exact same logic in a View that converts an n-dimensional RAInterval into a 1-dimensional RAInterval.  The RAccess on this would be what you implemented here, accepting 0/ ignoring the dimension parameter in setPosition, move and fwd, bck methods?  Also, please do not add curly brackets to single line loops.

**Comment by axtimwalde** [comment]
So it is mostly renaming, removing the LinearAccessible and LinearAccess interfaces and move the logic to RandomAccessibleInterval and RandomAccess implementations.

**Comment by hanslovsky** [comment]
I agree that keeping the number of interfaces as low as possible is desirable. However, having a (useless) dimension parameter for `setPosition` would be confusing. With good documentation the usage should be clear. I prefer just ignoring the dimension parameter for performance reasons.
What about `setPosition(long[])` and similar methods? Throw `UnsupportedOperationException`?
A good name for the `Views` method would then be `Views.flatten`.

**Comment by hanslovsky** [comment]
One thing that I do not like about using RAI instead of LinearAccessible is that method signatures will not tell the caller whether they expect an actual RAI or a flattened RAI.

**Comment by tpietzsch** [comment]
General question: Where is this useful where it cannot be replaced by (flat) iteration easily?

**Comment by hanslovsky** [comment]
I am working on a n-d watershed and for performance reasons (probably only true for `ArrayImg`) I would like to access a RAI in a linear fashion like an array.

**Comment by axtimwalde** [comment]
@tpietzsch iterables do not offer efficient modes of random access into a linearized index, being able to enumerate and access an integer coordinate by a single index can be useful, @hanslovskyp needs it for an efficient compact watershed implementation.  I do, though prefer the idea of not introducing a new interface but instead doing the same thing with RandomAccess, we can do that first outside ImgLib2 and if it turns out to be generic enough, think again about a pull request.

**Comment by tpietzsch** [comment]
What about adding index access to `Cursor`.

"`setPosition`" could be trivially implemented for existing cursors, even be added to the `Cursor` interface as a default method. Plus optimized implementations for `ArrayCursor` etc.

"`getPosition`" is not as trivial, but I'm sure it could be done without or with minimal overhead.

**Comment by tpietzsch** [comment]
and by the way: awesome that you are working on watershed! parallel?

**Comment by hanslovsky** [comment]
`getPosition` is not an immediate requirement and could be dropped. So we could just extend `Cursor` with a `setPosition` method. Extending an existing interface is a potentially big change. Do you think that (currently) single use case justifies this extension?

Unfortunately, no parallel watershed so far, but @axtimwalde and I certainly have that in mind and have discussed possible parallel solutions. So far we have not come up with a method that would be parallel and guarantee the same solution as a single threaded watershed on the whole volume, unfortunately.

**Comment by tpietzsch** [comment]
> getPosition is not an immediate requirement and could be dropped. So we could just extend Cursor with a setPosition method. Extending an existing interface is a potentially big change. Do you think that (currently) single use case justifies this extension?

I'm not sure. @axtimwalde @StephanPreibisch @dietzc @ctrueden what do you think? Would we have other use cases?

> Unfortunately, no parallel watershed so far, but @axtimwalde and I certainly have that in mind and have discussed possible parallel solutions. So far we have not come up with a method that would be parallel and guarantee the same solution as a single threaded watershed on the whole volume, unfortunately.

Yes, it's not straightforward. I was also thinking about it some time ago. It is related to component trees (obviously) and there are several papers about parallelizing that. All some variations of "do-something-stupid-locally-then-union-find-to-merge". It's no longer linear than but I could imagine it could even be an improvement in practice when running single-threaded, because you don't have to maintain large queues and access all over the place all the time.

**Comment by dietzc** [comment]
Ok, maybe it's a super stupid and naive question (caused by jetlag or whatever): but basically you want to have a first version of `reset()` + `jmpForward(int steps)` methods which are provided in the `Iterator` interface? why not add `setIndex(long idx)` to this interface which in the default implementation does `reset()` and `jumpFwd(...)` and in the special case (like `ArrayImg`) does it in a more efficient way?

PS: Concerning the watershed... maybe you can consolidate efforts with https://github.com/imagej/imagej-ops/pull/446.

**Comment by axtimwalde** [comment]
@tpietzsch we are currently interested in extensions of the watershed cost functions that make parallelization even harder, in particular two variants of 'compact watershed' where the Euclidean or geodesic distance to the respective seeds contributes to the cost.  For the 'classic' watershed, I believe that this approach

http://www.sciencedirect.com/science/article/pii/S0031320399001545

would enable straight forward parallelization?  Haven't tried yet.

We could add index access to cursor, but I am not yet sure that this is actually better than unfolding dimensions and sticking with `RandomAccess`.  I actually found myself wishing that I could unfold the third dimension into the second recently (to save volume blocks as JPG).  The 1-dimensional RandomAccess is the terminal case for this kind of flattening and we could make it available just so.  I like a `RandomAccess` solution for that it is consistent with the current thinking of random access vs. iteration.  I like the `Cursor` solution for that it does not ask you to pass arrays or dimension specifiers when you already know that there is only 1 dimension.

**Comment by tpietzsch** [comment]
@dietzc yes, that was exactly what I was thinking too!

**Comment by tpietzsch** [comment]
@axtimwalde a difference of `Cursor` solution vs `RandomAccess` is that `Cursor` indices are well-defined wrt the min of the interval. For min=(0,0,...) it's always easy, but to it is (to me) not immediately clear how to flatten dimensions for non-0-min intervals.

**Comment by tpietzsch** [comment]
> I believe that this approach
> 
> http://www.sciencedirect.com/science/article/pii/S0031320399001545
> 
> would enable straight forward parallelization? Haven't tried yet.

I don't know that paper. I'll have a look tomorrow!
Can you point me to papers regarding the " 'compact watershed' where the Euclidean or geodesic distance to the respective seeds contributes to the cost"?

**Comment by hanslovsky** [comment]
This is the original reference:
https://www.tu-chemnitz.de/etit/proaut/forschung/rsrc/cws_pSLIC_ICPR.pdf

Essentially, you remember the position of the seeds (or the number of steps you had to go so far to reach that pixel) and add that distance to the gray value difference.

**Comment by ctrueden** [comment]
> @ctrueden what do you think?

I just wonder why we need to have both `randomAccess()` and `cursor()` if they are both converging on the same API in the end?

**Comment by tpietzsch** [comment]
@ctrueden as @dietzc pointed out, you can already always "fake" `c.setPosition(n)` by `c.reset(); c.jumpFwd(n+1)`. The question is whether we want to add a (possibly more efficient) shortcut for that.

**Comment by ctrueden** [comment]
> you can already always "fake"

OK, right.

> The question is whether we want to add a (possibly more efficient) shortcut for that.

Makes sense to me!

**Comment by axtimwalde** [comment]
@tpietzsch @dietzc: @hanslovsky and me have discussed this again and we currently think that the `flatten`-ed accessible should be a `RandomAccessibleInterval` with `min=[0]`.  Reasons are:
* no change to the core API of ImgLib2,
* no inefficient default implementation that will depress developers and is aesthetically  unpleasing (see below),
* the index in `Cursor` is not a coordinate like in `RandomAccess`, i.e. localize on a `Cursor` is not expected to return the index but an n-dimensional location,
* `Cursor.reset()` sets the `Cursor` to index -1 instead 0 for making it compatible with Java's `Iterator` logic (`next()`, `hasNext()`), i.e. the default implementation for `setIndex(idx)` is `cursor.reset(); jumpFwd(++idx);`,
* the 0-coordinate of the `flatten`-ed `RandomAccessibleInterval` will map to the min corner of the source `RandomAccessibleInterval`, simple contract,
* we can extend the concept of flattening all dimensions to flattening one dimension into another

**Comment by dietzc** [comment]
> no change to the core API of ImgLib2. 

We could use Java8 default methods in interfaces to avoid any API breaks to implement default behaviour. The nice thing is that adding `setIndex(...)` in the `Iterator` make it easy for implementing classes like `ArrayImg` to offer an efficient implementation. If you would do it in `Views.flatten(...)` you would have to special case on a certain interface which you have to introduce or for each implementation on it's own to get efficient implementations. Maybe I'm missing something here.

Anyway, I totally see the use-cases now :+1:

**Pull request closed without merging**
