### PR TITLE
added long index based access methods with default int cast to all ac…

### PR DESCRIPTION
**Pull request by axtimwalde**
…cesses

This reduces code duplication for https://github.com/imglib/imglib2-unsafe/issues/1#issuecomment-291215338

### CODE REVIEW

**Comment by hanslovsky** [comment]
I don't see any issues with this and I think this can be merged.

**Comment by hanslovsky** [comment]
Actually, I thought about it a little more and I think this is not beneficial over an additional interface that extends the existing access interfaces with long index get and set methods and defaults the int index get and set methods to delegate to the long index get and set methods.

With this PR, one would need to implement 4 methods per access for long index accessing (including overwriting the default methods), whereas the interface hierarchy as it is right now in imglib2-unsafe only requires the implementaiton of 2 methods for that.

**Comment by axtimwalde** [comment]
... plus the interfaces.  We can count characters :).  How about using int-based accesses in long-assuming code?  Is that something that we want?  Sorry for the premature pull request.

**Comment by ctrueden** [comment]
Why not do things the other way, with the `int`-based methods being `default` and delegating to the `long` ones?

**Comment by hanslovsky** [comment]
This seems like the natural choice to me as well. There is one problem with this, however: All existing accesses would need to be updated. That is why I would prefer to introduce new interfaces that extend the existing accesses and add the `long` index `get` and `set` methods and default the `int` to delegate to the `long` ones.

**Comment by tpietzsch** [comment]
It doesn't look like this is supposed to be merged. Can it be closed?

**Pull request closed without merging**
