### PR TITLE
Fix  PlanarSubsetLocalzingCursor

### PR DESCRIPTION
**Pull request by dietzc**
position calculation was mixed between subset interval and global container.

### CODE REVIEW

**Comment by dietzc** [comment]
@tpietzsch for review. I included some tests.

**Comment by dietzc** [comment]
@tpietzsch any news on this? :-)

**Comment by tpietzsch** [comment]
@dietcz I'm just looking through it, and it looks like I opened a can of worms when looking around a bit... I'll skype you.

**Comment by dietzc** [comment]
I hate "opening can of worms". just ping me in skype whenever you like.

**Comment by dietzc** [comment]
I addressed several of the discussed issues. Only thing which needs more thought is the optimization of the `PlanarPlaneSubsetLocalizingCursor`, which could potentially made faster by making use of the fact, that we only process 2D images.

**Comment by tpietzsch** [comment]
@dietzc I updated `PlanarPlaneSubsetLocalizingCursor` to use that we only process a 2D (or 1D) slice.
The test still runs through, but could you test on more practical example if you have one?

**Comment by tpietzsch** [comment]
@dietzc any news on this?

**Comment by dietzc** [comment]
see: https://gitter.im/imagej/imagej-ops. I was asking @kephale to test it on his problem he had during the hackathon to validate that our fixes work.

**Comment by tpietzsch** [comment]
sooo... no news then?

**Comment by dietzc** [comment]
not yet. I asked again.

**Comment by kephale** [comment]
Looks fixed to me!

**Comment by tpietzsch** [comment]
thanks @dietzc @kephale !

**Pull request merged**
