### PR TITLE
added public access to primitive types for generic integer types

### PR DESCRIPTION
**Pull request by axtimwalde**
deprecated redundant protected get/setValue methods

### CODE REVIEW

**Comment by tpietzsch** [comment]
> @tpietzsch if you have not objections, I would like to merge imglib/imglib2#162 ASAP
will save me four obsolete special purpose implementations for copy between primitive arrays of unsigned integers and will also make this more efficient (no double & 0xff... and cast)

Why the renaming from `setValue()` to `setByte()` etc? Why not just make `setValue()` public instead of deprecating?

**Comment by axtimwalde** [comment]
@tpietzsch thanks for commenting:
1. to enable preserving the old getValue/ setValue methods in protected mode, i.e. do not change the API in terms of SemVer,
2. because it is more telling what the methods do, they are in fact all very different, no good reason to have them have the same name (at least in my eyes)

**Comment by tpietzsch** [comment]
Fair enough. Then I would ask you to remember to remove the deprecated methods a few releases down the line

**Comment by axtimwalde** [comment]
I promise!

**Comment by axtimwalde** [comment]
I will also write some comments.  Sorry for not having done so yet.

**Comment by tpietzsch** [comment]
👍  I'm fine with merging this then :-)

**Comment by axtimwalde** [comment]
Great! Thanks!

**Pull request merged**
