### PR TITLE
Add method for union of two intervals

### PR DESCRIPTION
**Pull request by bogovicj**
Re #124 
Very similar to the intersection method.
 ( "union" may not be the _best_ name, since its doesn't act like the union of sets - I'm thinking if the input is two non-overlapping intervals - but its probably clear enough )

### CODE REVIEW

**Comment by tpietzsch** [comment]
Maybe "smallestContainingInterval" is a better name? But I'd be also okay with "union" as it's shorter and, as you said, should be clear enough. Does anyone else have an opinion on this?

In any case, please fix the javadoc:
`Create a {@link FinalInterval} , which is the union of the input intervals (i.e., the area contained in either input interval).`
This is the description of actual "union", not what the method does.

**Comment by axtimwalde** [comment]
I share your initial feelings about the union, but it's used in the same spirit in https://docs.oracle.com/javase/7/docs/api/java/awt/Rectangle.html#union%28java.awt.Rectangle%29 therefore and in the interest of short names I am strongly pro union ;).

**Comment by bogovicj** [comment]
Then we'll stick with "union"
Javadoc edited!

**Comment by tpietzsch** [comment]
thanks @bogovicj

**Pull request merged**
