### PR TITLE
Add expand method to Intervals 

### PR DESCRIPTION
**Pull request by dietzc**
... which expands an `Interval` in in all dimensions given `Dimensions` object.

### CODE REVIEW

**Comment by hanslovsky** [comment]
Would it make sense to expand min and max differently?

**Comment by tpietzsch** [comment]
@hanslovsky I agree that vararg overload would be useful. Could you add this, @dietzc?

Expanding min and max differently:  I wouldn't do that. In that case you would pass an `Interval`, and use the distance of min/max to the origin to determine where you want to add what. But this would allow also to shrink and/or shift the interval. So `expand` isn't the right name for that. It might lead to confusion if you pass an `Interval` and expect it to be treated as a `Dimensions`.

**Comment by dietzc** [comment]
of course. like this?

**Comment by tpietzsch** [comment]
👍

**Comment by hanslovsky** [comment]
I just noticed, unfortunately after the PR was already merged: The added methods are not static.

**Comment by dietzc** [comment]
I'll fix it. Give me 1h.

**Comment by dietzc** [comment]
https://github.com/imglib/imglib2/commit/027f5090c2c493f58b584c2b3d2df8f8c29add6a

**Comment by hanslovsky** [comment]
That hour went by fast. :+1: Looks good to me!

**Pull request merged**
