### PR TITLE
added most simple implementation of integer shear transform

### PR DESCRIPTION
**Pull request by hanslovsky**
This transforms an n-dimensional coordinate c like this:
```java
c[ shearDimension ] = c[ shearDimension ] + c[ referenceDimension ]  // forward
c[ shearDimension ] = c[ shearDimension ] - c[ referenceDimension ]  // backward
```
Source and target dimensions are the same.

### CODE REVIEW

**Comment by axtimwalde** [comment]
Thanks @hanslovsky!  Can you add the methods

    RandomAccessibleInterval Views.shear(RandomAccessibleInterval, int, int)
    RandomAccessibleInterval Views.unshear(RandomAccessibleInterval, int, int)
    RandomAccessible Views.shear(RandomAccessible, int, int)
    RandomAccessible Views.unshear(RandomAccessible, int, int)

?  I think, then we're done and ready to merge.

Thanks

**Comment by hanslovsky** [comment]
I will do that.
As the Interval implementations will require Views.extend to avoid out of bounds errors, I will create
```java
RandomAccessibleInterval Views.shear(RandomAccessibleInterval, int, int, T) // use extendValue( source, T t )
RandomAccessibleInterval Views.shear(RandomAccessibleInterval, int, int ) // convenience for RealType, extend with Double.NaN
```

**Comment by axtimwalde** [comment]
@hanslovsky you're right, the dimensions change.  Instead of
    RandomAccessibleInterval Views.shear(RandomAccessibleInterval, int, int)
    RandomAccessibleInterval Views.unshear(RandomAccessibleInterval, int, int)
I suggest that we have
    RandomAccessibleInterval Views.shear(RandomAccessibel, Interval, int, int)
    RandomAccessibleInterval Views.unshear(RandomAccessible, Interval, int, int)
which would be more generic.  No shortcuts for RealType and NaN, RealType is not always Double and may not have NaN (intrinsic problem of RealType write inheritance being the same as read inheritance).

**Comment by hanslovsky** [comment]
I added the convenience methods to Views.

**Comment by axtimwalde** [comment]
@hanslovsky Couldn't find

    RandomAccessible Views.shear(RandomAccessible, int, int)
    RandomAccessible Views.unshear(RandomAccessible, int, int)

**Comment by hanslovsky** [comment]
Added that now.

**Comment by axtimwalde** [comment]
Thanks @hanslovsky this is a very useful addition!

**Pull request merged**
